//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryAutomation.Models.Orm
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookList
    {
        public int ID { get; set; }
        public string Book_Title { get; set; }
        public string Publisher { get; set; }
        public string Summary { get; set; }
        public string Language { get; set; }
        public string PageCount { get; set; }
        public Nullable<System.DateTime> PublisDate { get; set; }
        public Nullable<int> AuthorID { get; set; }
    
        public virtual AuthorList AuthorList { get; set; }
    }
}
